set tabstop=4
set shiftwidth=4
set expandtab
set backspace=indent,eol,start
set whichwrap+=<,>,h,l,[,]
set visualbell
fixdel

" Add indentation
set smartindent
set autoindent
set cindent

syntax on     " Enable syntax highlighting
set showmatch " Show matching brackets.
set title     " Add filename to titlebar
set number    " Show line numbers
set ruler     " Show row and column
